project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: about.qmd
        text: About
      - href: blogs.qmd
        text: Blog
        
  page-footer:
    right: "&copy; 2024, Taylor Kim"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
  

execute: 
  freeze: auto # only renders files you change 